[package]
name = "AoC2021"
version = "0.1.0"
authors = ["Matej Kerekrety <matej.kerekrety@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[example]]
name = "01"
path = "src/01_day.rs"
