[package]
name = "AoC2021"
version = "0.1.0"
authors = ["Matej Kerekrety <matej.kerekrety@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[[example]]
name = "11"
path = "src/11_day.rs"
